name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        node: ["18", "20", "22"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache turbo setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run CI with turbo
        run: pnpm run ci

      - name: Publish eslint-plugin-solid to npm if needed
        if: ${{ github.ref_name }} == "main"
        uses: JS-DevTools/npm-publish@v3
        with:
          package: ./packages/eslint-plugin-solid
          token: ${{ secrets.NPM_TOKEN }}
          strategy: upgrade
          access: public
          provenance: true
          # TODO remove
          dry-run: true

      - name: Publish eslint-solid-standalone to npm if needed
        if: ${{ github.ref_name }} == "main"
        uses: JS-DevTools/npm-publish@v3
        with:
          package: ./packages/eslint-solid-standalone
          token: ${{ secrets.NPM_TOKEN }}
          strategy: upgrade
          access: public
          provenance: true
          # TODO remove
          dry-run: true
