name: CI
on:
  push:
    branches-ignore:
      - reactivity-v2
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18", "20"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run build
      - name: Lint source code
        run: pnpm run lint --max-warnings=0
      - name: Run all tests
        run: pnpm run test:all
      - name: Sanity check standalone build
        working-directory: standalone
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm test
